version: '3.8'
services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=the_melvin_bank_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
    volumes:
      - postgres_data:/var/lib/postgres/data
#    env_file:
#      - ./postgres/postgres.env
    networks:
      - fraud_detection_net

  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_ENABLE_REMOTE_CONNECTIONS=true
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra/new_credit_card_fraud.csv:/home/new_credit_card_fraud.csv
      - ./cassandra/init.cql:/home/init.cql
#      - ./cassandra/init.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - fraud_detection_net

#  fraud_intelligence:
#    build: ./fraud_intelligence  # Builds from the Dockerfile in this directory
#    ports:
#      - "5000:5000"
#    networks:
#      - fraud_detection_network

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - fraud_detection_net

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./kafka/kafka.env:/etc/kafka/kafka.env
      - ./kafka/create-topics.sh:/opt/kafka/scripts
    depends_on:
      - zookeeper
    networks:
      - fraud_detection_net

  kafka-setup:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
    volumes:
      - ./kafka/create-topics.sh:/opt/kafka/scripts/create-topics.sh
    entrypoint: [ "sh", "-c", "/opt/kafka/scripts/create-topics.sh" ]
    networks:
      - fraud_detection_net

  nifi:
    build:
      context: ./nifi
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      SMTP_HOSTNAME: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: mineshmelvin@gmail.com
      # Password Generated from google account
      SMTP_PASSWORD: xdeh tqde sttc htdk
    depends_on:
      - postgres
      - kafka
      - cassandra
    networks:
      - fraud_detection_net

  spark:
    build:
      context: ./spark
    environment:
      - SPARK_MASTER_HOST=spark
    ports:
      - "7077:7077"
      - "4040:4040"
    depends_on:
      - kafka-setup
      - cassandra
    volumes:
      - ./spark:/app
#    command: [ "/entrypoint.sh" ]
    networks:
      - fraud_detection_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=hadesarchitect-cassandra-datasource  # Ensure the plugin name is correct
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
#    depends_on:
#      - cassandra
    networks:
      - fraud_detection_net

  flask-app:
    image: python:3.9-slim
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y libpq-dev gcc &&
      pip install -r requirements.txt &&
      flask run --host=0.0.0.0 --port=5000
      "
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - kafka
      - nifi
      - cassandra
      - spark
      - grafana
    networks:
      - fraud_detection_net

networks:
  fraud_detection_net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: